# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/projects/virtualpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/projects/virtualpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/projects/virtualpc/CMakeFiles /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/projects/virtualpc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/projects/virtualpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pc

# Build rule for target.
pc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pc
.PHONY : pc

# fast build rule for target.
pc/fast:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/build
.PHONY : pc/fast

src/cpu.o: src/cpu.c.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.c.o:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/cpu.c.o
.PHONY : src/cpu.c.o

src/cpu.i: src/cpu.c.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.c.i:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/cpu.c.i
.PHONY : src/cpu.c.i

src/cpu.s: src/cpu.c.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.c.s:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/cpu.c.s
.PHONY : src/cpu.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/main.c.s
.PHONY : src/main.c.s

src/mem.o: src/mem.c.o

.PHONY : src/mem.o

# target to build an object file
src/mem.c.o:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/mem.c.o
.PHONY : src/mem.c.o

src/mem.i: src/mem.c.i

.PHONY : src/mem.i

# target to preprocess a source file
src/mem.c.i:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/mem.c.i
.PHONY : src/mem.c.i

src/mem.s: src/mem.c.s

.PHONY : src/mem.s

# target to generate assembly for a file
src/mem.c.s:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/mem.c.s
.PHONY : src/mem.c.s

src/pc.o: src/pc.c.o

.PHONY : src/pc.o

# target to build an object file
src/pc.c.o:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/pc.c.o
.PHONY : src/pc.c.o

src/pc.i: src/pc.c.i

.PHONY : src/pc.i

# target to preprocess a source file
src/pc.c.i:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/pc.c.i
.PHONY : src/pc.c.i

src/pc.s: src/pc.c.s

.PHONY : src/pc.s

# target to generate assembly for a file
src/pc.c.s:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/pc.c.s
.PHONY : src/pc.c.s

src/vio/dev/term.o: src/vio/dev/term.c.o

.PHONY : src/vio/dev/term.o

# target to build an object file
src/vio/dev/term.c.o:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/vio/dev/term.c.o
.PHONY : src/vio/dev/term.c.o

src/vio/dev/term.i: src/vio/dev/term.c.i

.PHONY : src/vio/dev/term.i

# target to preprocess a source file
src/vio/dev/term.c.i:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/vio/dev/term.c.i
.PHONY : src/vio/dev/term.c.i

src/vio/dev/term.s: src/vio/dev/term.c.s

.PHONY : src/vio/dev/term.s

# target to generate assembly for a file
src/vio/dev/term.c.s:
	$(MAKE) -f CMakeFiles/pc.dir/build.make CMakeFiles/pc.dir/src/vio/dev/term.c.s
.PHONY : src/vio/dev/term.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... pc"
	@echo "... edit_cache"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mem.o"
	@echo "... src/mem.i"
	@echo "... src/mem.s"
	@echo "... src/pc.o"
	@echo "... src/pc.i"
	@echo "... src/pc.s"
	@echo "... src/vio/dev/term.o"
	@echo "... src/vio/dev/term.i"
	@echo "... src/vio/dev/term.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

